/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.VeiculoControl;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.StringVaziaException;
import model.Veiculo;

/**
 *
 * @author leleb
 */
public class FrmBuscaFiltrada extends javax.swing.JFrame {
    private VeiculoControl vectrl;
    private static FrmBuscaFiltrada frmbuscaFiltrada = null;
    /**
     * Creates new form FrmBuscaFiltrada
     */
    private FrmBuscaFiltrada() {
        initComponents();
        vectrl = new VeiculoControl();
    }
    
    public static FrmBuscaFiltrada getInstancia() {
    
        if (frmbuscaFiltrada==null)
            frmbuscaFiltrada = new FrmBuscaFiltrada();
        return frmbuscaFiltrada;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculos = new javax.swing.JTable();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        btnBuscarFiltro = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnBusca2 = new javax.swing.JButton();
        btnBuscaPlaca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Placa", "Cor", "Ano de Fabric."
            }
        ));
        jScrollPane1.setViewportView(tblVeiculos);

        lblAno.setText("Informe o ano:");

        lblMarca.setText("Informe a marca:");

        lblPlaca.setText("Informe o inicio da placa:");

        btnBuscarFiltro.setText("Buscar Ano");
        btnBuscarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFiltroActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        lblTitulo.setText("Busca com filtro");

        btnBusca2.setText(" Buscar Marca");
        btnBusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusca2ActionPerformed(evt);
            }
        });

        btnBuscaPlaca.setText("Buscar Placa");
        btnBuscaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarca)
                            .addComponent(lblPlaca)
                            .addComponent(lblAno))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtMarca)
                            .addComponent(txtAno)))
                    .addComponent(btnBuscarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAno)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlaca))
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscaPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiltroActionPerformed
        String marca  = this.txtMarca.getText();
        String placa  = this.txtPlaca.getText();
        String ano    = this.txtAno.getText();
       
        try{
            if ((marca.length()==0) && placa.length()==0 && ano.length()==0)
                throw new StringVaziaException();
            else {
                 ArrayList<Veiculo> lista;
                lista = vectrl.buscarAno(Integer.parseInt(ano));
                DefaultTableModel dados = (DefaultTableModel) tblVeiculos.getModel();
                dados.setNumRows(0);
                for (Veiculo ve: lista)
                {
                    dados.addRow(new Object[]{ve.getMarca(),ve.getModelo(),ve.getPlaca(),ve.getCor(),ve.getAnoFabricacao()});
                }           
             this.txtMarca.setText(" ");
             this.txtPlaca.setText(" ");
             this.txtAno.setText(" ");
        }
       } catch (StringVaziaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Preencha pelo menos um dos campos.",  JOptionPane.WARNING_MESSAGE );
       } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ano de fabricação inválido. Impossivel converter letras para números.", null,  JOptionPane.INFORMATION_MESSAGE);
            this.txtAno.setText(" ");
            this.txtAno.requestFocus();
       } catch (SQLException ex) {
            System.out.println ("Erro na busca " + ex.toString());
            JOptionPane.showMessageDialog(null,"Não foi possivel buscar os veículos! "+ex.toString());
       } catch (ClassNotFoundException ex) {
            System.out.println ("Erro de conexão " + ex.toString());
        }
    }//GEN-LAST:event_btnBuscarFiltroActionPerformed

    private void btnBusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusca2ActionPerformed
        String marca  = this.txtMarca.getText();
        String placa  = this.txtPlaca.getText();
        String ano    = this.txtAno.getText();
       
        try{
            if ((marca.length()==0) && placa.length()==0 && ano.length()==0)
                throw new StringVaziaException();
            else {
                 ArrayList<Veiculo> lista;
                lista = vectrl.buscarMarca(marca);
                DefaultTableModel dados = (DefaultTableModel) tblVeiculos.getModel();
                dados.setNumRows(0);
                for (Veiculo ve: lista)
                {
                    dados.addRow(new Object[]{ve.getMarca(),ve.getModelo(),ve.getPlaca(),ve.getCor(),ve.getAnoFabricacao()});
                }           
             this.txtMarca.setText(" ");
             this.txtPlaca.setText(" ");
             this.txtAno.setText(" ");
        }
       } catch (StringVaziaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Preencha pelo menos um dos campos.",  JOptionPane.WARNING_MESSAGE );
       } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ano de fabricação inválido. Impossivel converter letras para números.", null,  JOptionPane.INFORMATION_MESSAGE);
            this.txtAno.setText(" ");
            this.txtAno.requestFocus();
       } catch (SQLException ex) {
            System.out.println ("Erro na busca " + ex.toString());
            JOptionPane.showMessageDialog(null,"Não foi possivel buscar os veículos! "+ex.toString());
       } catch (ClassNotFoundException ex) {
            System.out.println ("Erro de conexão " + ex.toString());
        }
    }//GEN-LAST:event_btnBusca2ActionPerformed

    private void btnBuscaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPlacaActionPerformed
        String marca  = this.txtMarca.getText();
        String placa  = this.txtPlaca.getText();
        String ano    = this.txtAno.getText();
       
        try{
            if ((marca.length()==0) && placa.length()==0 && ano.length()==0)
                throw new StringVaziaException();
            else {
                 ArrayList<Veiculo> lista;
                lista = vectrl.buscarPlaca(placa);
                DefaultTableModel dados = (DefaultTableModel) tblVeiculos.getModel();
                dados.setNumRows(0);
                for (Veiculo ve: lista)
                {
                    System.out.println(ve.getPlaca());
                    dados.addRow(new Object[]{ve.getMarca(),ve.getModelo(),ve.getPlaca(),ve.getCor(),ve.getAnoFabricacao()});
                }           
             this.txtMarca.setText(" ");
             this.txtPlaca.setText(" ");
             this.txtAno.setText(" ");
        }
       } catch (StringVaziaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Preencha pelo menos um dos campos.",  JOptionPane.WARNING_MESSAGE );
       } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ano de fabricação inválido. Impossivel converter letras para números.", null,  JOptionPane.INFORMATION_MESSAGE);
            this.txtAno.setText(" ");
            this.txtAno.requestFocus();
       } catch (SQLException ex) {
            System.out.println ("Erro na busca " + ex.toString());
            JOptionPane.showMessageDialog(null,"Não foi possivel buscar os veículos! "+ex.toString());
       } catch (ClassNotFoundException ex) {
            System.out.println ("Erro de conexão " + ex.toString());
        }
    }//GEN-LAST:event_btnBuscaPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscaFiltrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscaFiltrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscaFiltrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscaFiltrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscaFiltrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca2;
    private javax.swing.JButton btnBuscaPlaca;
    private javax.swing.JButton btnBuscarFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVeiculos;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
